### ISSUE TITLE
jjk server

### ISSUE THREAD

**Issue by Frosty00000** [hadences/ProjectJJK-Issues#1]
I can't run the jjk mod on the server

**Comment by JustVibes44** [comment]
yeah the jjk mod is not working thus i only included fabric api and the jjk mod in the pack and it refuses to run the server resulting in crashes (on aternos anyway) so yeah please fix... here is the crash log https://mclo.gs/JnpHJSh

**Comment by Frosty00000** [comment]
Thanks

**Comment by hadences** [comment]
fixed
